version: '2'
services:
  broker-3:
    image: confluentinc/cp-kafka:4.0.0
    container_name: broker-3
    extra_hosts:
      - "zookeeper_1:172.31.32.10"
      - "zookeeper_2:172.31.0.10"
      - "zookeeper_2:172.31.80.10"
    env_file:
      - ./kafka-broker-3.env
    ports:
      - 39092:39092
    volumes:
      - /home/ubuntu/kafka/broker_3/data:/var/lib/kafka/data
