version: '2'
services:
  zookeeper-3:
    image: confluentinc/cp-zookeeper:4.0.0
    container_name: zookeeper-3
    extra_hosts:
      - "zookeeper_1:172.31.32.10"
      - "zookeeper_2:172.31.0.10"
      - "zookeeper_3:172.31.80.10"
    env_file:
      - ./zookeeper-3.env
    ports:
      - 42181:42181
      - 42888:42888
      - 43888:43888
    volumes:
      - /home/ubuntu/zookeeper_3/data:/var/lib/zookeeper/data
      - /home/ubuntu/zookeeper_3/logs:/var/lib/zookeeper/log

